<!--Some stuff that needs to go in a separate file-->
<?php
//Make a database connection
try {
$dba = new mysqli("localhost","root","");
} catch (\Exception $e) {
	echo $e->getMessage();
}
//If the connection is unable to select the database, point the browser to the install file
if ($dba->select_db('fyp') === false) {
	echo "Database not found error";;
}
mysqli_close($dba);
//Initialise main database connection
$db = new PDO('mysql:host=localhost;dbname=fyp;charset=utf8', 'root', '');

?>
<!--//////////////////////////////////////////////////-->



<!doctype HTML>
<html>

	<head>
		<title></title>
		<link rel="stylesheet" type="text/css" href="/css/main.css">
		<link rel="stylesheet" type="text/css" href="/css/table.css">
	</head>

	<body>
		<!--head-->
		<img src="header.png" class="htemplate">
		<!--/head-->

		<p>Here is the body of stuffs</p>
		<!--table-->
		<?php include 'table.html' ?>
		<!--/table-->
		

<!-- 		<?php
		//List most recent items. LIMIT decides how many items to show
		$sql = "SELECT DISTINCT username FROM fyp.availability LIMIT 50";
		//create an executable sql statement
		$stmt = $db->prepare($sql);
		//execute the statement
		$stmt->execute();

		//if there is no error, while there are rows to fetch, print out the item in that row
		if($stmt->errorCode() ==0) {
			while(($row = $stmt->fetch()) !=false) { 
		?>
			<div></br>Username: <?php echo $row['username']?></div>
		<?php	} 

		} else {
			$errors = $stmt->errorInfo();
			//prints out the error message held in position [2] of the array generated by errorInfo
			echo($errors[2]);
			echo 'Error retrieving usernames';
		}

		?> -->


<!-- 		<img src="footer.png" class="ftemplate"> -->
	</body>
</html>	